### PR TITLE
Feature/fusion tables

### PR DESCRIPTION
**Pull request by benwilhelm**
Removing the Wufoo service that we were originally planning for saving subscriber data. Using Google Fusion Tables instead.

@manleyjster can you take a look at these changes and tell me if you see any problems before I merge them in?

### CODE REVIEW

**Comment by justinmanley** [comment]
Hmmm. Reading through the code, it looks really good. 

`bin/poll` runs with the test phone number activated - but I'm not able to get it to run successfully hooked up to Google Fusion Tables. When I try to run it, I get an error: `[Error: error:0906D06C:PEM routines:PEM_read_bio:no start line]`. It seems to be an issue with the `.pem` file - but I can't figure it out (As far as I can tell, I followed the directions at [google/google-api-nodejs-client](https://github.com/google/google-api-nodejs-client#using-jwt-service-tokens) assiduously). 

Did you encounter this issue?

**Comment by benwilhelm** [comment]
Are you storing a path to the .pem file in the GOOGLE_AUTH_PEM environment
variable? It should actually be the contents of the pem file in that
variable.  Everything between and including the "BEGIN/END RSA KEY" lines.
You can replace the line breaks with \n.

On Mon, Apr 20, 2015 at 2:01 AM, Justin Manley notifications@github.com
wrote:

> Hmmm. Reading through the code, it looks really good.
> 
> bin/poll runs with the test phone number activated - but I'm not able to
> get it to run successfully hooked up to Google Fusion Tables. When I try to
> run it, I get an error: [Error: error:0906D06C:PEM
> routines:PEM_read_bio:no start line]. It seems to be an issue with the
> .pem file - but I can't figure it out (As far as I can tell, I followed
> the directions at google/google-api-nodejs-client
> https://github.com/google/google-api-nodejs-client#using-jwt-service-tokens
> assiduously).
> 
> Did you encounter this issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/open-city/kcbx-petcoke/pull/3#issuecomment-94375228.

## 

Ben Wilhelm
ben@doublebeamdesign.com

**Comment by justinmanley** [comment]
Hmmm. That's not what the documentation suggests: https://github.com/google/google-api-nodejs-client/#using-jwt-service-tokens.

**Comment by justinmanley** [comment]
Hmmm. Not sure what's going on - when I try putting the content of the .pem file in, I get an `invalid_grant` error.

In any case, I filed an issue: https://github.com/google/google-api-nodejs-client/issues/418.

**Comment by benwilhelm** [comment]
Ah, sorry. The critical piece that I forgot to tell you is that the jwt client will accept either a path to the pem file or the pem key. The documentation is showing the path to pem file, but the parameter 'null' immediately following it is where you would pass the key itself.  So your initialization would be:

```
var jwtClient = new google.auth.JWT(
  'serviceaccount@email.com',
  null, // this is where you were previously passing the path
  process.env.GOOGLE_AUTH_PEM, // this holds the key itself
  [scope1, scope2],
  'bar@subjectaccount.com'
);
```

I did it this way to avoid having to commit the PEM file, since we can't store files persistently on heroku.

Ben

**Comment by justinmanley** [comment]
yup, that was it. Still not getting it to work, but it's closer - now I get an `[Error: unauthorized_client]`. I figure it's some issue with my configuration / permissions.

**Pull request merged**
